remote_theme: vaibhavvikas/jekyll-theme-minimalistic
plugins:
  - jekyll-remote-theme

title: Gestor de Biblioteca Web
description: Documentación técnica

# Sidebar navigation
navigation:
  - name: Inicio
    link: ./index.html
  - name: Introducción
    link: ./introduccion.html
  - name: Instalación
    link: ./instalacion.html
  - name: Uso
    link: ./uso.html
  - name: Arquitectura
    link: ./arquitectura.html
  - name: Conclusiones
    link: ./conclusiones.html
  - name: Referencias
    link: ./referencias.html
