title: Mi proyecto intermodular
description: Documentaci√≥n del proyecto intermodular
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
show_downloads: false
markdown: kramdown
