title: Gestor de Biblioteca Web
description: Documentación técnica del proyecto intermodular
theme: jekyll-theme-cayman

header_pages:
  - index.md
  - introduccion.md
  - instalacion.md
  - uso.md
  - arquitectura.md
  - conclusiones.md
  - referencias.md
